POST http://localhost:3333/courses
Content-Type: application/json

{
  "title":  "Curso de Java"
}

###

GET  http://localhost:3333/courses

###

GET  http://localhost:3333/courses/9147c7d8-f4b0-43ab-ab34-6c5b82074f5e
